openapi: 3.0.0

info:
    title: Delilah Resto
    version: 1.0.0
paths:
  /: # debería ser delilah.resto.com.ar?
    get:
        description: 'devuelve la página principal'
        responses: 
          200:
            description: 'la página es accesible'
          404:
            description: 'hubo un error'
  /login:
    get:
      description: 'obtiene la página de inicio'
    post:
      description: 'envía información de inicio de sesión'
  /users/{id}:
    description: 'ver perfil'
    # debería ir acá adentro el 
  /admins:
    description: 'ver los pedidos'
