openapi: 3.0.0

info:
    title: Delilah Resto
    version: 1.0.0
paths:
  /: # debería ser delilah.resto.com.ar?
    get:
        description: 'devuelve la página principal'
        responses: 
          200:
            description: 'la página es accesible'
          404:
            description: 'hubo un error'
  /login:
    get:
      description: 'obtiene la página de inicio'
    post:
      description: 'envía información de inicio de sesión'
  /register:
    get:
      description: 'obtiene la página para registrarse'
        responses:
          200:
            description: 'OK'
          400:
            description: 'Bad input information'
          500:
            description: 'Internal server error'
    post:
      description: 'envía la información para el registro'
      produces: 'application/json'
      parameters:
      
  
  /users/{id}:
    description: 'ver perfil'
    # debería ir acá adentro el 
  /admins:
    description: 'ver los pedidos'

  /orders:
  /order:
    description: 'make an order'
    /confirmation:
    /status:
  /login:
  /register:
  /users:
  /admin:
  /login:
